sudo: required

services:
  - docker

before_install:
  - docker build -t dariusz151/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dariusz151/docker-react npm test

after_success:
  - docker build -t dariusz151/multi-client ./client
  - docker build -t dariusz151/multi-nginx ./nginx
  - docked build -t dariusz151/multi-server ./server
  - docker build -t dariusz151/multi-worker ./worker
    #login do docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push to docker hub
  - docker push dariusz151/multi-client
  - docker push dariusz151/multi-nginx
  - docker push dariusz151/multi-server
  - docker push dariusz151/multi-worker
